### ISSUE TITLE
Change position of the WaveView

### ISSUE THREAD

**Issue by TPeterW** [recruit-lifestyle/WaveSwipeRefreshLayout#10]
I love this library thank you! One thing though, how would I go about changing the position of the refresh indicator (the ball as shown below, the position doesn't change)?

<img width="343" alt="screenshot 2015-10-29 21 18 29" src="https://cloud.githubusercontent.com/assets/9685093/10836356/dd105b2e-7e82-11e5-9756-b8351178089c.png">

    swipeRefreshLayout.setMaxDropHeight(10);

I tried setMaxDropHeight but it doesn't work, is it the problem with newer versions?

**Comment by TPeterW** [comment]
I'm using target idk 23 and build tools 23.0.1

**Comment by amyu** [comment]
I'm sorry it is late to notice!
Please wait a minute!!!

**Comment by amyu** [comment]
Thanks @jmatsu !!!

**Comment by jmatsu** [comment]
@TPeterW 
In WaveView#setMaxDropHeight(int *height*),
*height* represents the offset from the top of WaveSwipeRefreshLayout.
It's not from *the bottom of the animated wave* so the given *height* should be higher than the height of *the wave*.
If a shortage of *height* is specified, it will be ignored and the warning message will be shown on LogCat.

According to your example, you tried to set '10' as the height.
In generally, '10' is very small, so it will be ignored.

It's a feature, not a bug.
Try to set larger integer.
