### ISSUE TITLE
Set top offset for wave animation

### ISSUE THREAD

**Issue by MFlisar** [recruit-lifestyle/WaveSwipeRefreshLayout#16]
I want to use the layout in fullscreen mode with transparent toolbar and statusbar, where the content is visible underneath the toolbar and statusbar. So I would need the `SwipeResfreshLayout` to fill the screen (because it's scrollable content fills the screen as well and is visible underneath the toolbar and statusbar), but the wave animation should start underneath the toolbar.

Is this somehow possible?

**Comment by amyu** [comment]
Thanks @MFlisar 

Sorry, I have not been able to grasp the situation.
Please give source code or screenshots.

Thank you.

**Comment by MFlisar** [comment]
Here's a short video demonstrating the current behaviour that (as far as I saw) can't be solved via any setting:

https://www.dropbox.com/s/7t3wylln19e3hq4/SCR_20160121_085905.mp4?dl=0

I tried to change the layout params of the internal `WaveView` and tried to add a padding, but actually the `LayoutParams` type of it does not support it...

**Comment by amyu** [comment]
@MFlisar 

Thank you!  

```xml
dependencies {
  compile 'com.github.recruit-lifestyle:WaveSwipeRefreshLayout:1.5'
}
```
If you added version1.5, you can use ```WaveSwipeRefreshLayout#setTopOffsetWave ``` method!

Please refer to the following
https://github.com/recruit-lifestyle/WaveSwipeRefreshLayout/blob/master/sample/src/main/java/jp/co/recruit_lifestyle/sample/MainActivity.java#L46-L52

**Comment by MFlisar** [comment]
Awesome, works great, thanks

**Comment by amyu** [comment]
It was the urgent implementation.
Please contact us if there is a bug.
