### ISSUE TITLE
it's not an issue 

### ISSUE THREAD

**Issue by MahdouaniYessine** [recruit-lifestyle/WaveSwipeRefreshLayout#18]
Can i change the refreshing from the top to the botton? (instead up/down refreshing down/up)

**Comment by amyu** [comment]
Thanks @MahdouaniYessine !

I made this View while referring to the SwipeRefreshLayout.
For that reason, You can not change the refreshing from the top to the bottom.

But, If you want it, I might implement!!!!!!
At that time, Please make the Issue!
Thank you!

**Comment by MahdouaniYessine** [comment]
Thank you, 
Yes, if you can implement the refreshing from the bottom, it will help me.
Thanks in advance :)

**Comment by amyu** [comment]
(๑•̀ㅂ•́)و✧

**Comment by MahdouaniYessine** [comment]
!!!
