### ISSUE TITLE
Transparent color not working

### ISSUE THREAD

**Issue by MFlisar** [recruit-lifestyle/WaveSwipeRefreshLayout#19]
It seems like the view has it's own background... When using a transparent color for the wave, I can't see what's behind the wave but it looks like seeing the default background behind it...

I have a "workaround" for now, just using a solid color and make the `WaveView` transparent itself works.

    int transparency = 200;
    Color cSolid = Color.rgb(255, 0, 0);
    Color c = Color.argb(transparancy, 255, 0, 0);

**Not working**

    srl.setWaveColor(c);

**Working**

    srl.setWaveColor(cSolid);

 	try
	{
		Field field = WaveSwipeRefreshLayout.class.getDeclaredField("mWaveView");
		field.setAccessible(true);
		View view = (View)field.get(srl);
		view.setAlpha((float)transparency/255f);
	} 
	catch (NoSuchFieldException e)
	{
		e.printStackTrace();
	}
	catch (IllegalAccessException e)
	{
		e.printStackTrace();
	}

**Comment by amyu** [comment]
Thanks @MFlisar !

Please wait a minute.
I will check it!!!!!

**Comment by amyu** [comment]
@MFlisar 

Thank you!  

```xml
dependencies {
  compile 'com.github.recruit-lifestyle:WaveSwipeRefreshLayout:1.6'
}
```
I have fixed a bug that sets the alpha value!
Please contact us if there is a bug ლ(´ڡ`ლ)
