### ISSUE TITLE
Custom color - instead of blue

### ISSUE THREAD

**Issue by iSimar** [recruit-lifestyle/WaveSwipeRefreshLayout#2]
Great library.

How can I use another color for the drop, instead of blue?

**Comment by amyu** [comment]
Thank you!  

```xml
dependencies {
  compile 'com.github.recruit-lifestyle:WaveSwipeRefreshLayout:1.2'
}
```
If you added version1.2, you can use ```WaveSwipeRefreshLayout#setWaveColor``` method!

**Comment by iSimar** [comment]
Awesome, thank you.

**Comment by hatpick** [comment]
How do you set the color of rotating arrow?

**Comment by hatpick** [comment]
can you make it like I can use colors with alpha? (in setWaveColor switch mPaint.setColor to setARGB)

**Comment by amyu** [comment]
@hatpick 

```xml
dependencies {
  compile 'com.github.recruit-lifestyle:WaveSwipeRefreshLayout:1.4'
}
```
If you added version1.4, you can use ```WaveSwipeRefreshLayout#setWaveARGBColor``` method!

**Comment by hatpick** [comment]
Thanks,

**Comment by scascacha** [comment]
This works perfectly! But is there a way to change the Arrow color?

**Comment by SamaludheenCignes** [comment]
use setColorSchemeColors(color)
