### ISSUE TITLE
Error:Could not find com.github.recruit-lifestyle:WaveSwipeRefreshLayout:1.6

### ISSUE THREAD

**Issue by Isabellle** [recruit-lifestyle/WaveSwipeRefreshLayout#25]
Error:Could not find com.github.recruit-lifestyle:WaveSwipeRefreshLayout:1.6.
Required by:
    weatherApp:app:unspecified
<a href="searchInBuildFiles">Search in build.gradle files</a>

**Comment by amyu** [comment]
@Isabellle 
Please try it!

**Comment by Isabellle** [comment]
It works fine! But I think I was guilty, I put the jitpack dependency to buildscript instead of allprojects. Everything runs smoothly. Thanks.

**Comment by amyu** [comment]
Thanks @Isabellle 
Please contact us if there is a bug ლ(´ڡ`ლ)
