### ISSUE TITLE
The drop goes under the screen

### ISSUE THREAD

**Issue by reversecoder** [recruit-lifestyle/WaveSwipeRefreshLayout#26]
In my screen I have a recyclerview and the recyclerview is placed in the middle of the screen. That's why while I am pulling for refresh the drop goes under the screen that is not visible to user. I want to show the drop in the visible screen.

Any help will be appreciated.

**Comment by amyu** [comment]
Thanks @reversecoder 

Sorry, I have not been able to grasp the situation.
Is it the fact that you use the WaveSwipeRefreshLayout in Fragment?
In order to understand quickly, please source code or sample project! ლ(´ڡ`ლ)

**Comment by amyu** [comment]
Please re- create again Issue!
