### ISSUE TITLE
Thanks for your work.I want to know how to change this color from black to white?

### ISSUE THREAD

**Issue by BranZhang** [recruit-lifestyle/WaveSwipeRefreshLayout#28]
![qq 20160820222434](https://cloud.githubusercontent.com/assets/10242480/17831779/5513641e-6725-11e6-82eb-969668977a33.png)

**Comment by amyu** [comment]
Thanks @BranZhang !

Please, try it!

```
mWaveSwipeRefreshLayout.setColorSchemeColors(Color.BLUE);
```

Use
https://github.com/recruit-lifestyle/WaveSwipeRefreshLayout/blob/master/library/src/main/java/jp/co/recruit_lifestyle/android/widget/WaveSwipeRefreshLayout.java#L584
or 
https://github.com/recruit-lifestyle/WaveSwipeRefreshLayout/blob/master/library/src/main/java/jp/co/recruit_lifestyle/android/widget/WaveSwipeRefreshLayout.java#L577

**Comment by BranZhang** [comment]
it works!
thanks a lot.

**Comment by amyu** [comment]
Thanks @BranZhang !

Please contact us if there is a bug ლ(´ڡ`ლ)
