### ISSUE TITLE
drop disappears on changing orientation

### ISSUE THREAD

**Issue by iSimar** [recruit-lifestyle/WaveSwipeRefreshLayout#4]
Hello there 

When you change the orientation of the phone - from landscape to portrait or vice versa while the drop is loading, it disappears. Shouldn't it rotate with the screen?

Regards,

**Comment by amyu** [comment]
Thank you.  

I made this View while referring to the SwipeRefreshLayout.
But, I plan to soon the corresponding!  

Please wait a little more!

**Comment by iSimar** [comment]
Cool, looking forward to it. 

Thanks

**Comment by luizfp** [comment]
Any updates on this?

Thanks
