### ISSUE TITLE
Hello WaveSwipeRefreshLayout include Recyclerview problem scroll up when always refreshing

### ISSUE THREAD

**Issue by xesun** [recruit-lifestyle/WaveSwipeRefreshLayout#6]
<jp.co.recruit_lifestyle.android.widget.WaveSwipeRefreshLayout
        android:id="@+id/main_swipe"
        android:layout_width="match_parent"
        android:layout_height="match_parent">

        <com.marshalchen.ultimaterecyclerview.UltimateRecyclerView
            android:id="@+id/listView"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            app:recyclerviewScrollbars="vertical" />
    </jp.co.recruit_lifestyle.android.widget.WaveSwipeRefreshLayout>

**Comment by amyu** [comment]
Thank you.

I tried to implement the RecyclerView.
[issue#6-include-Recyclerview-problem](https://github.com/recruit-lifestyle/WaveSwipeRefreshLayout/tree/issue%236-include-Recyclerview-problem) branch.
But I could not confirm it.

Please explain it to me more.

**Comment by xesun** [comment]
Thank you Amyu
