### ISSUE TITLE
hi sorry WaveswiperefreshLayout container recyclerview problem fix please help me 

### ISSUE THREAD

**Issue by xesun** [recruit-lifestyle/WaveSwipeRefreshLayout#7]
Scroll when refreshing why
    <mn.slide.ubinfo.view.pulltorefresh.WaveSwipeRefreshLayout
        android:id="@+id/refreshLayout"
        android:layout_width="match_parent"
        android:layout_height="match_parent">

        <com.marshalchen.ultimaterecyclerview.UltimateRecyclerView
            android:id="@+id/listView"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:scrollbars="vertical" />
    </mn.slide.ubinfo.view.pulltorefresh.WaveSwipeRefreshLayout>

**Comment by amyu** [comment]
I made this View while referring to the SwipeRefreshLayout.
If UltimateRecyclerView can use SwipeRefreshLayout, you can WaveSwipeRefreshLayout.

I think this problem is in the UltimateRecyclerView.

**Comment by xesun** [comment]
Thanks

**Comment by Rainer-Lang** [comment]
@xesun Did you solve it? I also use URV.
