### ISSUE TITLE
refresh from bottom?

### ISSUE THREAD

**Issue by TheLoyalCruel** [recruit-lifestyle/WaveSwipeRefreshLayout#8]
thanks for this beautiful library :)
is it possible to refresh a list from bottom of it?

**Comment by amyu** [comment]
Thanks!

It is not possible to refresh a list from bottom of this library...
This Library is expressed an animation that water droplets fall.
So I did not implement it.
If necessary, I think I try to implement when there is a time.

Thank you.

**Comment by TheLoyalCruel** [comment]
I have another question!
would you please help me to remove the line behind the appbar and recycler view?
I mean this shadow:
![screenshot_2015-09-07-21-02-38](https://cloud.githubusercontent.com/assets/10336613/9720555/58242de8-55a4-11e5-8115-98c0c674f216.png)

and this is my testapp:
https://github.com/TheLoyalCruel/TestApp
please take a look... 
thanks a million :)

**Comment by amyu** [comment]
Thanks!

Let me check and get back to you as soon as possible!

**Comment by amyu** [comment]
I understood it.

It is problem of TabLayout.
If you build  API 21↓, you can see no shadow.
But if you build API21↑ , you can see shadow of TabLayout!

This problem is my unruly.
Sorry.

amyu
